overrides/assets/javascripts/diagrams.js
Fixes:
* Correct one of the identical sub-expressions on both sides of operator "&&"
* 'zip_qhead' is not modified in this loop.
=> Fix sonarqube errors

docs/playbooks/how-to-get-started/index.md
Creating the "New Developer" Playbook back
=> New Developer Playbook  Page

docs/activities/documentation/updating-this-site.md, snippets/abbreviations.md
To add a missing step from the instructions
You need to get an AD Group added
=> Adding the AD task for joining the repo

mkdocs.development.yml, overrides/partials/footer.html
* We need to allow users to provide feedback on the content of the site.
* Added a link to an MS forms page asking for feedback, this is publicly accessible.
=> Feedback form

docs/playbooks/10-Discovery-Playbook/10-starting-a-discovery.md, docs/playbooks/10-Discovery-Playbook/20-what-to-do-in-discovery.md
* Changed from being "asked" to do a discovery to identifying a new user issue to explore.
=> Clarified reasons for starting a discovery

custom/formatter.py, overrides/assets/javascripts/slideshow.js, overrides/assets/stylesheets/slideshow.css
* Prefixes all ids inside svgs with the filename to avoid duplicate id references
* Add aria labels and roles to the UI components
=> Fix: svg embedded elements

docs/activities/documentation/updating-this-site.md
* Added a note about joining the github organisation is not self serve.
=> Added note on self serve

docs/activities/test-resources/index.md
Because it is different to the CIN test envs
1 sentence and a link to the list of people that need to be contacted
I've added DID to the abbreviations but don't know how to add that to this PR, so it is another one, sorry
=> Adding instructions for accessing the Model Office

snippets/abbreviations.md
Adding DID to the abbreviations
Because I reference it somewhere else
=> Adding DID to the abbreviations

custom/formatter.py, docs/activities/documentation/updating-this-site.md, overrides/assets/javascripts/diagrams.js, overrides/assets/stylesheets/accessibility.css, overrides/assets/stylesheets/theme.css, pull_request_template.md
* Add accessibility requirements to pull request task list
* Add escape shortcut to exit zoomed diagrams.
* Improve contrast ratio to 7:1 for most content.
* Fix the tab ordering of text size and colour theme in top menu
=> Accessibility Improvements

docs/playbooks/how-to-get-started/index.md
- Text
- Images
- Audio
- Video
=> fix typos on how to get started page

docs/activities/test-resources/index.md, snippets/abbreviations.md
- Text
- Images
- Audio
- Video
=> Changing the CIN names on the Activities page

mkdocs.yml, overrides/assets/javascripts/slideshow.js
* Make slide controls comes before slides in tab order
* Remove on page heading links to fix render issues with JAWS
- Text
- Images
- Audio
- Video
=> Accessibility fixes

snippets/abbreviations.md
* Add DDEI to abbreviations file
- Text
- Images
- Audio
- Video
=> Add DDEI abbreviation

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/content-request.yml
* Add an issue template for reporting bugs
* Add an issue template for requesting new content
* Disable creating blank issues
* Signpost security issues to CPS cyber team
- Text
- Images
- Audio
- Video
=> Add issue templates

custom/emoji.py, docs/activities/diagramming/index.md, docs/activities/diagramming/software.md, docs/activities/documentation/kitchen-sink.md, docs/playbooks/Lifecycle/10-Discovery-Playbook/20-what-to-do-in-discovery.md, docs/playbooks/Lifecycle/10-Discovery-Playbook/index.md, docs/playbooks/Lifecycle/20-Alpha-Playbook/10-meeting-the-service-standard.md, docs/playbooks/Lifecycle/20-Alpha-Playbook/index.md, docs/playbooks/Lifecycle/30-Beta-Playbook/10-meeting-the-service-standard.md, docs/playbooks/Lifecycle/30-Beta-Playbook/index.md, docs/playbooks/Lifecycle/40-Live-Playbook/index.md, docs/playbooks/Lifecycle/50-Retirement-Playbook/index.md, mkdocs.yml, overrides/assets/javascripts/slideshow.js, pull_request_template.md
* Reordering the slideshow control components so visual matches tab order
* Add programmatic alt text to emojis
* Add guidance on how to make admonitions accessible
* Add guidance on making diagrams accessible
- Text
- Images
- Audio
- Video
=> Accessibility audit remediation

custom/emoji.py, docs/activities/diagramming/software.md, docs/activities/documentation/kitchen-sink.md, snippets/abbreviations.md
* Added guidance on creating text descriptions of diagrams
* Updated C4 and mermaid diagrams with descriptive text
* Fixed variable reassignment in custom emoji formatter
- Text
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Content: diagram descriptions

docs/activities/documentation/kitchen-sink.md, docs/standards/accessibility/creating-accessibility-statement/index.md, docs/standards/accessibility/creating-accessibility-statement/our-accessibility-statement.md, overrides/assets/stylesheets/accessibility.css, overrides/partials/footer.html, pull_request_template.md, snippets/abbreviations.md
* Add an initial draft accessibility statement
* Add a small gap to the top of the sidebar navigation to allow speech recognition
- Text
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Accessibility statement

docs/index.md
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Added text to define the scope of this website

.github/scripts/git-file-update-dates.sh, .github/workflows/admin-monthly.yml
* Create a new issue the first monday of every month with a random selection of content pages older than one month to check if updates are needed.
- Text
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Monthly Checkin Issue

docs/Strategy/index.md
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Added DID strategy page

docs/index.md
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Add link to strategy from home

docs/reports/index.md
* To upload service standard assessment reports.
* Created reports folder to upload service standard assessment reports.
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Add reports page for Service Standard Assessment reports

docs/reports/index.md
* To add text to explain the reports page for users. 
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Added covering note to Reports Index.md page

docs/reports/index.md
* Text needed to be updated. 
- Text
- Slide Shows
- Admonitions
- Diagrams
- Images
- Audio
- Video
=> Update reports covering note in index.md page
